### ISSUE TITLE
exeption when press help translate button

### ISSUE THREAD

**Issue by lzk228** [space-wizards/SS14.Launcher#154]
[14:17:13 DBG] Commit took: 00:00:00.0057397
Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at SS14.Launcher.ViewModels.LanguageSelectorViewModel.OnHelpTranslateButtonPressed() in /home/lzk/Documents/GitHub/SS14.Launcher/SS14.Launcher/ViewModels/LanguageSelectorViewModel.cs:line 76
   at Avalonia.Data.Converters.MethodToCommandConverter.Execute(Object parameter)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
   at Avalonia.Input.InputElement.<>c.<.cctor>b__32_9(InputElement x, PointerReleasedEventArgs e)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers, IInputElement hitTest)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.ManualRawEventGrouperDispatchQueue.DispatchNext()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.DesktopApplicationExtensions.Run(Application app, CancellationToken token)
   at Avalonia.Controls.DesktopApplicationExtensions.Run(Application app, Window mainWindow)
   at SS14.Launcher.Program.AppMain(Application app, String[] args) in /home/lzk/Documents/GitHub/SS14.Launcher/SS14.Launcher/Program.cs:line 298
   at Avalonia.AppBuilder.Start(AppMainDelegate main, String[] args)
   at SS14.Launcher.Program.Main(String[] args) in /home/lzk/Documents/GitHub/SS14.Launcher/SS14.Launcher/Program.cs:line 130

**Comment by lzk228** [comment]
fixed by https://github.com/space-wizards/SS14.Launcher/pull/155
